/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ventass;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author olive
 */
public class inicio extends javax.swing.JFrame {

    private ArrayList<Producto> listarProductos = new ArrayList();
    private ArrayList<Venta> listarVentas = new ArrayList();
    private DefaultTableModel modeloTabla1 = new DefaultTableModel();
    private DefaultTableModel modeloTabla2 = new DefaultTableModel();
    private DefaultTableModel modeloTabla3 = new DefaultTableModel();

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        botones1 = new javax.swing.ButtonGroup();
        productos = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codigoProducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescripcionProducto = new javax.swing.JTextArea();
        PrecioUnitarioProducto = new javax.swing.JTextField();
        guardarP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        codigoVendedor = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaVendedor = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        codigoProductoVendedor = new javax.swing.JComboBox<>();
        ventas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fechaVenta = new javax.swing.JTextField();
        numVendedorVentas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigoProductoVentas = new javax.swing.JComboBox<>();
        cantidadVendidaVentas = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        comboBoxEfectivo = new javax.swing.JRadioButton();
        ComboBoxDebito = new javax.swing.JRadioButton();
        comboBoxTarjeta = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textoVendedorMasAlto = new javax.swing.JLabel();
        textoMontoTotalVendedorMasAlto = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoVentaMayorTarjeta = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ventasPorDebito = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosMouseClicked(evt);
            }
        });

        jLabel5.setText("Codigo");

        jLabel7.setText("Descripción");

        jLabel8.setText("Precio unitario");

        DescripcionProducto.setColumns(20);
        DescripcionProducto.setRows(5);
        jScrollPane2.setViewportView(DescripcionProducto);

        guardarP.setText("Guardar producto");
        guardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPActionPerformed(evt);
            }
        });

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Precio unitario", "Descripcion"
            }
        ));
        jScrollPane3.setViewportView(TablaProductos);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Registrar producto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarP)
                .addGap(77, 77, 77))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PrecioUnitarioProducto))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PrecioUnitarioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(guardarP)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        productos.addTab("Productos", jPanel3);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Consulta por vendedor ");

        codigoVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        codigoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoVendedorActionPerformed(evt);
            }
        });

        jLabel11.setText("Selecciona el vendedor");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Venta", "Vendedor", "Fecha", "Codigo de producto", "Cantidad", "Total"
            }
        ));
        jScrollPane4.setViewportView(tablaVendedor);

        jLabel15.setText("Codigo de producto a buscar");

        codigoProductoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProductoVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoProductoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButton2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(codigoProductoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButton2)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        productos.addTab("Vendedor", jPanel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Registro de ventas");

        jLabel1.setText("Fecha de venta");

        numVendedorVentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        numVendedorVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numVendedorVentasActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de vendedor");

        jLabel3.setText("Codigo de producto");

        jLabel4.setText("Cantidad Vendida");

        botones1.add(comboBoxEfectivo);
        comboBoxEfectivo.setText("Efectivo");
        comboBoxEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEfectivoActionPerformed(evt);
            }
        });

        botones1.add(ComboBoxDebito);
        ComboBoxDebito.setText("Debito");

        botones1.add(comboBoxTarjeta);
        comboBoxTarjeta.setText("Tarjeta");

        jLabel9.setText("Forma de pago");

        jButton1.setText("Registrar venta");
        jButton1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jButton1AncestorRemoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventasLayout = new javax.swing.GroupLayout(ventas);
        ventas.setLayout(ventasLayout);
        ventasLayout.setHorizontalGroup(
            ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventasLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6))
                    .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ventasLayout.createSequentialGroup()
                            .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fechaVenta)
                                .addComponent(numVendedorVentas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(codigoProductoVentas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantidadVendidaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventasLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(ventasLayout.createSequentialGroup()
                        .addComponent(ComboBoxDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ventasLayout.setVerticalGroup(
            ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numVendedorVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codigoProductoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadVendidaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxEfectivo)
                    .addComponent(jLabel9)
                    .addComponent(ComboBoxDebito)
                    .addComponent(comboBoxTarjeta))
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        productos.addTab("Ventas", ventas);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("VENDEDOR CON MÁS VENTAS");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Consultar");

        jLabel17.setText("El vendedor con mas ventas es:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("MONTO TOTAL DE VENTA");

        jLabel19.setText("El monto total acumulado es:");

        textoVendedorMasAlto.setText("____");

        textoMontoTotalVendedorMasAlto.setText("____");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("VENTA MAYOR CON TARJETA");

        textoVentaMayorTarjeta.setEditable(false);
        textoVentaMayorTarjeta.setColumns(20);
        textoVentaMayorTarjeta.setRows(5);
        jScrollPane1.setViewportView(textoVentaMayorTarjeta);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("VENTAS POR DÉBITO");

        ventasPorDebito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero vendedor", "Fecha", "Producto", "Total"
            }
        ));
        jScrollPane5.setViewportView(ventasPorDebito);

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoVendedorMasAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(250, 250, 250)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoMontoTotalVendedorMasAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(61, 61, 61))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textoVendedorMasAlto)
                    .addComponent(jLabel19)
                    .addComponent(textoMontoTotalVendedorMasAlto))
                .addGap(33, 33, 33)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(34, 34, 34))
        );

        productos.addTab("Consultas", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(productos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String obtenerRadioSeleccionado() {
        for (Enumeration<AbstractButton> buttons = botones1.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    
    
    private void comboBoxEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEfectivoActionPerformed

    private void numVendedorVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numVendedorVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numVendedorVentasActionPerformed

    private void codigoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoVendedorActionPerformed

    private void guardarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPActionPerformed
        // TODO add your handling code here:
        modeloTabla1.setColumnIdentifiers(new Object[]{"Codigo", "Precio Unitario", "Descripcion"});
        TablaProductos.setModel(modeloTabla1);
        modeloTabla1.setRowCount(0);
        try {
            Producto  nuevoProducto = new Producto(Integer.parseInt(codigoProducto.getText()), DescripcionProducto.getText(), Integer.valueOf(PrecioUnitarioProducto.getText())); 
            listarProductos.add(nuevoProducto);
            
            for (Producto p : listarProductos) {
                modeloTabla1.addRow(new Object[]{p.getCodigo(), p.getPrecioUnitario(), p.getDescripcion()});
            }
            codigoProductoVentas.addItem(nuevoProducto.getCodigo()+"");
            codigoProductoVendedor.addItem(nuevoProducto.getCodigo()+"");
            JOptionPane.showMessageDialog(null, "Se Completo el guardado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo Completar el guardado");
        }
    }//GEN-LAST:event_guardarPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            int cantidadVentas = listarVentas.size();
            String opcion = obtenerRadioSeleccionado();
        if (opcion == "Efectivo"){
            listarVentas.add(new Venta(fechaVenta.getText(),Integer.parseInt(numVendedorVentas.getSelectedItem().toString()),
                Integer.parseInt(codigoProductoVentas.getSelectedItem().toString()),(int) cantidadVendidaVentas.getValue(),0,cantidadVentas+1));
        }if (opcion == "Debito"){
            listarVentas.add(new Venta(fechaVenta.getText(),Integer.parseInt(numVendedorVentas.getSelectedItem().toString()),
                Integer.parseInt(codigoProductoVentas.getSelectedItem().toString()),(int) cantidadVendidaVentas.getValue(),1,cantidadVentas+1));
        }
        if (opcion == "Tarjeta"){
            listarVentas.add(new Venta(fechaVenta.getText(),Integer.parseInt(numVendedorVentas.getSelectedItem().toString()),
                Integer.parseInt(codigoProductoVentas.getSelectedItem().toString()),(int) cantidadVendidaVentas.getValue(),2,cantidadVentas+1));
        }
        System.out.println(opcion);
        JOptionPane.showMessageDialog(null, "Se Completo la Venta");
        }catch (Exception e){
        JOptionPane.showMessageDialog(null, "No se pudo Completar la Venta");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AncestorAdded

    private void jButton1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AncestorRemoved

    private void codigoProductoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProductoVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProductoVendedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        modeloTabla2.setColumnIdentifiers(new Object[]{ "Codigo Venta", "Vendedor" ,"Fecha", "Codigo de producto","Cantidad","Total"});
        tablaVendedor.setModel(modeloTabla2);
        modeloTabla2.setRowCount(0);
        ArrayList<Venta> ventaPorVendedor = new ArrayList<>();
        Producto precioU = listarProductos.get(Integer.parseInt(codigoProductoVendedor.getSelectedItem().toString()));
        for (Venta v : listarVentas) {
            if(     (   Integer.parseInt(   codigoVendedor.getSelectedItem().toString())== v.getCodigoVendedor()   )       && 
                    (Integer.parseInt(codigoProductoVendedor.getSelectedItem().toString()) == v.getCodigoProducto())){
            ventaPorVendedor.add(v);
            }
        }
        for (Venta v: ventaPorVendedor) {
                modeloTabla2.addRow(new Object[]{v.getCodigoVenta(), v.getCodigoVendedor(), v.getFechaVenta(),v.getCodigoProducto(),v.getCantidadVendida(),v.getPrecioFinal(precioU.getPrecioUnitario()) });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo Completar la Consulta");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
modeloTabla3.setColumnIdentifiers(new Object[]{"Numero vendedor", "Fecha", "Producto", "Total"});
ventasPorDebito.setModel(modeloTabla3);
modeloTabla3.setRowCount(0);

ArrayList<Venta> listarVentasPorDebito = new ArrayList<>();
for (Venta v : listarVentas) {
    if (v.getFormaPago() == 1) {
        listarVentasPorDebito.add(v);
    }
}

for (Venta v : listarVentasPorDebito) {
    Producto precioU = null;
    for (Producto p : listarProductos) {
        if (p.getCodigo() == v.getCodigoProducto()) {
            precioU = p;
            break;
        }
    }

    if (precioU != null) {
        modeloTabla3.addRow(new Object[]{
                v.getCodigoVendedor(), v.getFechaVenta(),
                v.getCodigoProducto(), v.getPrecioFinal(precioU.getPrecioUnitario())
        });
    }
}

// Usar un HashMap para almacenar las ventas de cada vendedor
Map<Integer, Double> ventasPorVendedor = new HashMap<>();
Venta ventaMayorConTarjeta = null;

for (Venta venta : listarVentas) {
    Producto precioU = null;
    for (Producto p : listarProductos) {
        if (p.getCodigo() == venta.getCodigoProducto()) {
            precioU = p;
            break;
        }
    }

    if (precioU != null) {
        double precioFinal = venta.getPrecioFinal(precioU.getPrecioUnitario());
        
        // Registrar ventas por vendedor
        ventasPorVendedor.put(venta.getCodigoVendedor(),
                ventasPorVendedor.getOrDefault(venta.getCodigoVendedor(), 0.0) + precioFinal);

        // Determinar la venta de mayor importe con tarjeta de crédito
        if (venta.getFormaPago() == 2) {
            if (ventaMayorConTarjeta == null || precioFinal > ventaMayorConTarjeta.getPrecioFinal(precioU.getPrecioUnitario())) {
                ventaMayorConTarjeta = venta;
            }
        }
    }
}

// Encontrar el mejor vendedor
int mejorVendedor = -1;
double maxVentas = 0;

for (Map.Entry<Integer, Double> entry : ventasPorVendedor.entrySet()) {
    if (entry.getValue() > maxVentas) {
        maxVentas = entry.getValue();
        mejorVendedor = entry.getKey();
    }
}

// Calcular la suma de ventas del mejor vendedor
double suma = ventasPorVendedor.getOrDefault(mejorVendedor, 0.0);
System.out.println("El vendedor con más ventas es: " + mejorVendedor + " con " + suma);

// Mostrar la venta mayor con pago por tarjeta
if (ventaMayorConTarjeta != null) {
    System.out.println("Venta mayor con tarjeta de crédito:");
    System.out.println("Fecha: " + ventaMayorConTarjeta.getFechaVenta());
    System.out.println("Vendedor: " + ventaMayorConTarjeta.getCodigoVendedor());
    System.out.println("Producto: " + ventaMayorConTarjeta.getCodigoProducto());

    Producto precioU = null;
    for (Producto p : listarProductos) {
        if (p.getCodigo() == ventaMayorConTarjeta.getCodigoProducto()) {
            precioU = p;
            break;
        }
    }

    if (precioU != null) {
        System.out.println("Total: " + ventaMayorConTarjeta.getPrecioFinal(precioU.getPrecioUnitario()));
    }
} else {
    System.out.println("No se registraron ventas con tarjeta de crédito.");
}

textoVendedorMasAlto.setText(mejorVendedor+"");
textoMontoTotalVendedorMasAlto.setText(suma+"");
textoVentaMayorTarjeta.setText(ventaMayorConTarjeta.getCodigoVendedor()+"");
System.out.println("El vendedor con más ventas es: " + mejorVendedor + " con " + suma);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_productosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ComboBoxDebito;
    private javax.swing.JTextArea DescripcionProducto;
    private javax.swing.JTextField PrecioUnitarioProducto;
    private javax.swing.JTable TablaProductos;
    private javax.swing.ButtonGroup botones1;
    private javax.swing.JSpinner cantidadVendidaVentas;
    private javax.swing.JTextField codigoProducto;
    private javax.swing.JComboBox<String> codigoProductoVendedor;
    private javax.swing.JComboBox<String> codigoProductoVentas;
    private javax.swing.JComboBox<String> codigoVendedor;
    private javax.swing.JRadioButton comboBoxEfectivo;
    private javax.swing.JRadioButton comboBoxTarjeta;
    private javax.swing.JTextField fechaVenta;
    private javax.swing.JButton guardarP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<String> numVendedorVentas;
    private javax.swing.JTabbedPane productos;
    private javax.swing.JTable tablaVendedor;
    private javax.swing.JLabel textoMontoTotalVendedorMasAlto;
    private javax.swing.JLabel textoVendedorMasAlto;
    private javax.swing.JTextArea textoVentaMayorTarjeta;
    private javax.swing.JPanel ventas;
    private javax.swing.JTable ventasPorDebito;
    // End of variables declaration//GEN-END:variables
}
